# Generated by Django 4.2.9 on 2024-02-18 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_thenotifications_user_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_key',
            field=models.CharField(default='', max_length=300),
        ),
    ]
