# Generated by Django 4.2.9 on 2024-02-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_access_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='AI_Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=1000)),
                ('key', models.CharField(max_length=2000)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
