# Generated by Django 4.2.9 on 2024-02-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_ai_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='ai_task',
            name='access_key',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
