# Generated by Django 4.2.9 on 2024-05-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_ai_task_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='ai_task',
            name='not_start_task',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
