# Generated by Django 4.2.9 on 2024-05-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_ai_task_not_start_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="dark_mode",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
