# Generated by Django 4.2.9 on 2024-10-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_user_ldap'),
    ]

    operations = [
        migrations.AddField(
            model_name='thenotifications',
            name='section',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='dark_mode',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
