# Generated by Django 4.2.9 on 2024-10-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_thenotifications_section_alter_user_dark_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='thenotifications',
            name='type',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
